const test = require('node:test');
const assert = require('node:assert/strict');
const { parseCents, parseInteger, validProducts, validProduct } = require('../model.js');
const product = () => ({codigo:1,nome:'Água mineral',precoCompraCentavos:150,precoVendaCentavos:300,quantidade:10});
test('decimal comma produces exact integer cents', () => assert.equal(parseCents('12,50', 'Preço'),1250));
test('decimal point produces exact integer cents', () => assert.equal(parseCents('0.29', 'Preço'),29));
test('one fractional digit and whole amounts', () => {assert.equal(parseCents('1,5','Preço'),150);assert.equal(parseCents('12','Preço'),1200);});
test('negative, nonfinite and ambiguous prices are rejected', () => {for(const v of ['-1','NaN','Infinity','1.000,00','1,234','1e3','','.50']) assert.throws(()=>parseCents(v,'Preço'));});
test('price limit is checked', () => {assert.equal(parseCents('100000,00','Preço'),10000000);assert.throws(()=>parseCents('100000,01','Preço'));});
test('zero price is valid', () => assert.equal(parseCents('0','Preço'),0));
test('integer code range and syntax', () => {assert.equal(parseInteger('101','Código',1,2147483647),101);for(const v of ['0','-1','1.5','1e2','2147483648','']) assert.throws(()=>parseInteger(v,'Código',1,2147483647));});
test('stock accepts zero but rejects negative values', () => {assert.equal(parseInteger('0','Quantidade',0,100000),0);assert.throws(()=>parseInteger('-1','Quantidade',0,100000));});
test('valid products are accepted', () => assert.equal(validProduct(product()),true));
test('duplicate product codes are rejected', () => assert.equal(validProducts([product(),product()]),false));
test('persisted data rejects negative and fractional values', () => {for(const key of ['quantidade','precoCompraCentavos','precoVendaCentavos']) for(const value of [-1,0.5,Infinity]) assert.equal(validProduct({...product(),[key]:value}),false);});
test('UTF-8 name limit is enforced', () => {assert.equal(validProduct({...product(),nome:'a'.repeat(99)}),true);assert.equal(validProduct({...product(),nome:'á'.repeat(50)}),false);});
test('empty, numeric-only and control-character names rejected', () => {for(const nome of ['','  ','123','Agua\n']) assert.equal(validProduct({...product(),nome}),false);});
test('persisted data must be a bounded array', () => {assert.equal(validProducts({}),false);assert.equal(validProducts(null),false);assert.equal(validProducts(Array.from({length:1001},(_,i)=>({...product(),codigo:i+1}))),false);});
test('empty catalog is valid', () => assert.equal(validProducts([]),true));
